module(load="imfile")

# Apache access log monitoring
input(type="imfile"
      file="/var/log/apache2/vulnerable-app-access.log"
      tag="apache-access"
      severity="info"
      facility="local2")

# Bash audit log forwarding
local1.* @192.168.56.102:514

# Apache access log forwarding
local2.* @192.168.56.102:514
